### ISSUE TITLE
Authorisation problem - can you please help?

### ISSUE THREAD

**Issue by AJJCAIRNS** [stevedsun/notion-graph-view#1]
Traceback (most recent call last):
  File "D:\PycharmProjects\notion-graph-view\main.py", line 26, in <module>
    read_page(my_token_v2, my_url)
  File "D:\PycharmProjects\notion-graph-view\main.py", line 10, in read_page       
    client = NotionClient(token_v2=token_v2)
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.p
y", line 95, in __init__
    self._update_user_info()
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.p
y", line 126, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.p
y", line 265, in post
    response.raise_for_status()
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\requests\models
.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.
notion.so/api/v3/loadUserContent

**Comment by AJJCAIRNS** [comment]
Remove curly brackets in the config file and it connects
