### ISSUE TITLE
nicodeEncodeError: 'charmap'

### ISSUE THREAD

**Issue by Cusssy** [stevedsun/notion-graph-view#21]
Graph is generated at: ./graph_out.html
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion_graph\__main__.py", line 4, in <module>
    cli.main()
  File "C:\Users\alber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion_graph\cli.py", line 17, in main
    parser.export_to_html(args.out)
  File "C:\Users\alber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion_graph\parser.py", line 53, in export_to_html
    self._graph.show(file_path)
  File "C:\Users\alber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyvis\network.py", line 551, in show
    self.write_html(name, local)
  File "C:\Users\alber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyvis\network.py", line 508, in write_html
    out.write(self.html)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 263607-263621: character maps to < undefined >

**Comment by DenGuzawr22** [comment]
I get the same error

**Comment by DenGuzawr22** [comment]
You need to add the created integration to the page connections
![image](https://github.com/stevedsun/notion-graph-view/assets/55553082/b8342f07-b589-444d-a704-6339d30e73b8)

**Comment by Sajo8** [comment]
Also having this issue

**Comment by debug420** [comment]
Still getting the issue

**Comment by stevedsun** [comment]
Fixed #27
