### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by serjanbiogenic** [stevedsun/notion-graph-view#9]
Hello! Did everything as instructed, getting these errors, please advise! thank you!

Traceback (most recent call last):
  File "C:\Users\###\Desktop\notion\main.py", line 1, in <module>
    from parser import BlockParser
  File "C:\Users\###\Desktop\notion\parser.py", line 2, in <module>
    from config import notion
  File "C:\Users\###\Desktop\notion\config.py", line 2, in <module>
    from notion_client import Client
ModuleNotFoundError: No module named 'notion_client'

**Comment by stevedsun** [comment]
Hello, from your error message, it seems you haven't completely installed dependencies. 
Can you run 'pip install -r requirements.txt` and paste the stdout message?

**Comment by rohansripad** [comment]
Hi - Do you know what I'm doing wrong here?

File "main.py", line 1, in <module>
    from parser import BlockParser
  File "/Usersxyz/Github/notion-graph-view/parser.py", line 238, in <module>
    class Graph:
  File "/Usersxyz/Github/notion-graph-view/parser.py", line 271, in Graph
    def get_graph(self) -> dict[str, list]:
TypeError: 'type' object is not subscriptable

**Comment by stevedsun** [comment]
Hi all,

This project has been updated to the latest Notion API version. And I also publish it to Pypi, you can install it by 

```
pip install notion-graph
```

And following the README to finish your work.

Thanks for using.
